# Natural Language Processing Lab
### Experiment 2: Corpus Exploration & Sentiment Analysis using Twitter Samples
**Name:** Khan Yahya Shahid Ali  
**UIN:** 221A048  
**Roll No:** 28  
---

In [1]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

import nltk
from nltk.corpus import twitter_samples
import matplotlib.pyplot as plt
import random

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

#download twitter sample dataset
nltk.download('twitter_samples')

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

[nltk_data] Downloading package twitter_samples to /root/nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!

True

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

import nltk
from nltk.corpus import twitter_samples

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

#load the dataset
tweets = twitter_samples.strings()
type(tweets)

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

list

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

len(tweets)

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

30000

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

import pandas as pd
all_tweets=pd.DataFrame(tweets,columns = ["Tweets"])
all_tweets.head()

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

                                              Tweets
0                                hopeless for tmr :(
1  Everything in the kids section of IKEA is so c...
2  @Hegelbon That heart sliding into the waste ba...
3  “@ketchBurning: I hate Japanese call him "bani...
4           Dang starting next week I have "work" :(

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

"len of first",len(tweets[0])

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

('len of first', 19)

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

twitter_samples.fileids()

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

['negative_tweets.json', 'positive_tweets.json', 'tweets.20150430-223406.json']

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

#select the set of pos and neg
positive_tweets = twitter_samples.strings('positive_tweets.json')
negative_tweets = twitter_samples.strings('negative_tweets.json')

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

len(positive_tweets)

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

5000

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

len(negative_tweets)

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

5000

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

positive_tweets=pd.DataFrame(positive_tweets, columns=["Positive "])
positive_tweets['Sentiments']='positive'
positive_tweets.tail()

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

                                              Positive  Sentiments
4995  @chriswiggin3 Chris, that's great to hear :) D...   positive
4996  @RachelLiskeard Thanks for the shout-out :) It...   positive
4997            @side556 Hey!  :)  Long time no talk...   positive
4998  @staybubbly69 as Matt would say. WELCOME TO AD...   positive
4999  @DanielOConnel18 you could say he will have eg...   positive

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

negative_tweets=pd.DataFrame(negative_tweets, columns=['Negative Tweets'])
negative_tweets['Sentiments']='Negative'
negative_tweets.tail()

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

                                        Negative Tweets Sentiments
4995               I wanna change my avi but uSanele :(   Negative
4996                         MY PUPPY BROKE HER FOOT :(   Negative
4997           where's all the jaebum baby pictures :((   Negative
4998  But but Mr Ahmad Maslan cooks too :( https://t...   Negative
4999  @eawoman As a Hull supporter I am expecting a ...   Negative

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

tweets=pd.concat([positive_tweets,negative_tweets],ignore_index= False)
tweets=tweets.sample(frac=1).reset_index(drop=True)
tweets

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

,Positive,Sentiments,Negative Tweets
0,NaN,Negative,Take me back to Dubai :(
1,NaN,Negative,@bcwgaming ffs didn't even know :(\nWhat time?
2,NaN,Negative,@Jae0409 cuz I thought we could ask team snapc...
3,NaN,Negative,so hard to not have contacts and you want to t...
4,goodnight I love everyone but hate myself beca...,positive,NaN
...,...,...,...
9995,#FollowFriday @murtishaw @aqui_fr @FRTechStart...,positive,NaN
9996,"@BrandonHerrigan Welcome :), when's your next ...",positive,NaN
9997,@mgallizzi it was a great read Matthew! Really...,positive,NaN
9998,"@Insane_chorri don't worry, aapke benchmarks k...",positive,NaN
9999,@BhaktisBanter this lovely black &amp; red Max...,positive,NaN

In [ ]:
# Student Details: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28
print("Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28")

tweets[tweets['Sentiments']=='positive'].value_counts().sum()
tweets[tweets['Sentiments']=='Negative'].value_counts().sum()

Name: Khan Yahya Shahid Ali | UIN: 221A048 | Roll No: 28

np.int64(0)